name: Default-Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      # numba is listed in requirements.txt so we need to remove it below.
      run: |
        conda create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file tests/requirements.txt
        source activate TEST
        conda uninstall numba
        pip install -e . --no-deps --force-reinstall

    - name: Debug conda
      shell: bash -l {0}
      run: |
        source activate TEST
        conda info --all
        conda list

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        pytest --disable-warnings
